export enum EBookingStatus {
  // ก่อนกด
  WAITING_QUEUE_APPROVAL = "WAITING_QUEUE_APPROVAL",
  WAITING_DEPOSIT_TRANSFER = "WAITING_DEPOSIT_TRANSFER",
  WAITING_DEPOSIT_VERIFY = "WAITING_DEPOSIT_VERIFY",
  QUEUE_BOOKED = "QUEUE_BOOKED",
  WAITING_BOOKING_INFO = "WAITING_BOOKING_INFO",
  TRANSFERRING_TICKET = "TRANSFERRING_TICKET",
  CONFIRMING_TICKET = "CONFIRMING_TICKET",
  WAITING_ADMIN_CONFIRM = "WAITING_ADMIN_CONFIRM",
  READY_TO_BOOK = "READY_TO_BOOK",

  // ระหว่างกด
  BOOKING_IN_PROGRESS = "BOOKING_IN_PROGRESS",
  PARTIALLY_BOOKED = "PARTIALLY_BOOKED",
  FULLY_BOOKED = "FULLY_BOOKED",
  BOOKING_FAILED = "BOOKING_FAILED",

  // ลูกค้าได้เอง
  CUSTOMER_SELF_BOOKED = "CUSTOMER_SELF_BOOKED",
  TEAM_NOT_RECEIVED = "TEAM_NOT_RECEIVED",
  TEAM_BOOKED = "TEAM_BOOKED",
  PARTIAL_SELF_TEAM_BOOKING = "PARTIAL_SELF_TEAM_BOOKING",

  // การเงิน
  WAITING_SERVICE_FEE = "WAITING_SERVICE_FEE",
  WAITING_SERVICE_FEE_VERIFY = "WAITING_SERVICE_FEE_VERIFY",
  SERVICE_FEE_PAID = "SERVICE_FEE_PAID",

  // มัดจำ
  DEPOSIT_PENDING = "DEPOSIT_PENDING",
  DEPOSIT_USED = "DEPOSIT_USED",
  DEPOSIT_FORFEITED = "DEPOSIT_FORFEITED",
  WAITING_REFUND = "WAITING_REFUND",
  REFUNDED = "REFUNDED",

  // ปิดงาน
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  CLOSED_REFUNDED = "CLOSED_REFUNDED",
}
